# Generated by Django 2.1.4 on 2018-12-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadtype',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
